### ISSUE TITLE
NullPointerException in FireTVService$Subscription

### ISSUE THREAD

**Issue by softvision-ionutgavris** [ConnectSDK/Connect-SDK-Android-FireTV#2]
We usually call selectedDevice.getCapability(MediaControl.class).subscribePlayState(null);

As you can see the listener is null for this request. Other services check for null listeners.
In my opinion the FireTVService should not add null listeners in the listeners ArrayList.

java.lang.NullPointerException: Attempt to invoke interface method 'void com.connectsdk.service.capability.listeners.ResponseListener.onSuccess(java.lang.Object)' on a null object reference
            at com.connectsdk.service.FireTVService$Subscription$1.run(FireTVService.java:636)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:155)
            at android.app.ActivityThread.main(ActivityThread.java:5696)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1028)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:823)

**Comment by softvision-ionutgavris** [comment]
https://github.com/ConnectSDK/Connect-SDK-Android-FireTV/pull/3

**Comment by oleksii-frolov** [comment]
The test was added for this case here https://github.com/ConnectSDK/Connect-SDK-Android-FireTV/commit/40e2e533e2228b9cac4465cb969c953eba068561
